# Ansible Inventory Template (inventory.tpl)
# Generated by Terraform to connect to the cluster
# Uses private IPs for internal nodes and proxy command via Bastion Host

[all:vars]
ansible_user=ubuntu
# Use the local SSH agent to establish a proxy connection
ansible_ssh_common_args=-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyCommand="ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -W %h:%p -q ubuntu@${bastion_public_ip}"

[bastion]
bastion ansible_host=${bastion_public_ip}

[bastion:vars]
ansible_ssh_common_args='' # Overrides proxy jump for the bastion itself

[kube-master]
master-node ansible_host=${master_private_ip}

[kube-workers]
worker-node-1 ansible_host=${worker_private_ips[0]}
worker-node-2 ansible_host=${worker_private_ips[1]}

[kube-nodes:children]
kube-master
kube-workers

[kube-nodes:vars]
# Variables for Kubernetes setup
ansible_python_interpreter=/usr/bin/python3