# These outputs provide the necessary connection details and security references
# for operational tasks (e.g., retrieving the key, running Ansible, testing connectivity).

# --- 1. Security Artifacts ---

output "cluster_private_key_location" {
  description = "The local filename where the cluster's private SSH key has been saved. This file is REQUIRED for all SSH/Ansible connections."
  value       = local_file.private_key_file.filename
}

# --- 2. Connection Details ---

output "bastion_public_ip" {
  description = "The public IP address of the Bastion Host. This is the only node accessible from the internet."
  value       = module.cluster_nodes.bastion_public_ip
}

output "bastion_ssh_command_tip" {
  description = "Example command to SSH into the Bastion Host. Replace ./cluster_key.pem with your retrieved key path."
  value       = "ssh -i ./cluster_key.pem ubuntu@${module.cluster_nodes.bastion_public_ip}"
}

output "master_node_private_ip" {
  description = "The private IP address of the Kubernetes Master Node (for confirmation/debugging)."
  value       = module.cluster_nodes.master_private_ip
}

output "ansible_inventory_file_path" {
  description = "The path to the Ansible inventory file, dynamically generated by Terraform for configuration execution."
  value       = "./inventory"
}

# --- 3. Infrastructure Details ---

output "provisioned_vpc_id" {
  description = "The ID of the primary VPC provisioned for the Kubernetes cluster."
  value       = module.k8s_vpc.vpc_id
}

# Expose the public subnet CIDR block from the module
output "vpc_cidr_block_used" {
  description = "The main CIDR block used by the VPC."
  value       = module.k8s_vpc.vpc_cidr_block_used
}


